tags:
  Hexo: "#0E834D"
  CSS: "#5298d1"
  Git: "#F14E32"
  Python: "#3776ab"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  Java: "#4d3900"
  TypeScript: "#317AC6"

head:
  css:
    remix-icon: https://chitangcos.zyglq.cn/css/remixicon.css

font:
  cdn:
    enable: true
    lib:
      - https://fonts.sourcegcdn.com/css2?family=Noto%20Serif
      - https://fonts.sourcegcdn.com/css2?family=JetBrains%20Mono
  serif:
    family: '''Noto Serif CJK SC'', ''Noto Serif'', ''Noto Serif SC'', ''宋体'', ''SimSun'', serif'
  sans_serif:
    family: '''MiSans'', sans-serif'
  monospace:
    family: '''JetBrainsMono Nerd Font'', ''FiraCode Nerd Font'', ''JetBrains Mono'', ''Fira Code'', ''Consolas'', monospace'

preload:
  style:
    - /css/hexo-theme-yun.css
  script:
    - /js/utils.js
    - /js/hexo-theme-yun.js

prefetch:
  script:
    - /js/sidebar.js

dns_prefetch:
  - https://cos.yunyoujun.cn
  - https://chitangcos.zyglq.cn

preconnect:
  - https://fastly.jsdelivr.net
  - https://chitangcos.zyglq.cn

social:
  - name: RSS
    link: /atom.xml 
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/chitang233
    icon: ri:github-line
    color: "#181717"
  - name: E-Mail
    link: mailto:me@chitang.dev
    icon: ri:mail-line
    color: "#8E71C1"
  - name: Telegram
    link: https://t.me/chitang233
    icon: ri:telegram-line
    color: "#0088CC"
  - name: Telegram Channel
    link: https://chitang.studio
    icon: ri:telegram-fill
    color: "#0088CC"
  - name: Matrix
    link: https://matrix.to/#/@sbchitang:matrix.org
    icon: ri:chat-smile-fill
    color: "#000000"
#  - name: Travelling
#    link: https://travellings.link
#    icon: ri:send-plane-2-line
#    color: black


banner:
  enable: true
  title: 池塘的博客
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: false

mode: auto

bg_image:
  enable: false
  url: biat
  # dark:
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  domain: blog.chitang.dev

search:
  modal: true
  bg_image: https://chitangcos.zyglq.cn/images/bg/stars-timing-2.jpg
  # dark_bg_image: xxx
  # placeholder:

trianglify:
  enable: true
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"

scrollreveal:
  enable: true
  targets:
    - .post-card
    - .markdown-body img

favicon: https://chitangcos.zyglq.cn/images/favicon.png


cursor:
  enable: true
  default: https://chitangcos.zyglq.cn/css/md-cursors/pointer.cur
  pointer: https://chitangcos.zyglq.cn/css/md-cursors/link.cur
  text: https://chitangcos.zyglq.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://chitangcos.zyglq.cn/images/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

avatar:
  enable: true
  url: https://chitangcos.zyglq.cn/images/avatar.webp
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: false

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    # - type: categories
    #   path: /categories/
    #   icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: 你猜
  # custom:
  #   title: Github
  #   path: https://github.com/chitang233
  #   icon: ri:github-line

pages:
  - name: 友链
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

post_card:
  opacity: 0.8

types:
  link:
    color: blue
    icon: ri:external-link-line
  bilibili:
    color: "#FF8EB3"
    icon: ri:bilibili-line
  github:
    color: black
    icon: ri:github-line
  netease-cloud-music:
    color: "#C10D0C"
    icon: ri:netease-cloud-music-line
  notion:
    color: black
    icon: ri:notion
  twitter:
    color: "#1da1f2"
    icon: ri:twitter-line
  weibo:
    color: "#E6162D"
    icon: ri:weibo-line
  zhihu:
    color: "#0084FF"
    icon: ri:zhihu-line

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

post_edit:
  enable: true
  url: https://github.com/chitang233/chitang233/tree/hexo/source/

codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

creative_commons:
  license: by-sa
  post: true
  language: deed.zh
  clipboard: false

lazyload:
  enable: true

reward:
  enable: false
  icon: ri:hand-coin-line
  comment: 给点饭钱
  methods:
     - name: 爱发电
       path: https://chitangcos.zyglq.cn/images/QRCodes/afdian.png
       color: "#7b5bc3"
       icon: /icon/afdian.png
#    - name: 支付宝
#      path: /images/QRCodes/alipay.png
#      color: "#00A3EE"
#      icon: ri:alipay-line
#    - name: QQ 支付
#      path: /images/QRCodes/qq.png
#      color: "#12B7F5"
#      icon: ri:qq-line
#    - name: 微信支付
#      path: /images/QRCodes/wechat.png
#      color: "#2DC100"
#      icon: ri:wechat-pay-line

footer:
  since: 2020
  icon:
    name: ri:cloud-line
    animated: true
    color: "#0078E7"
  powered:
    enable: version
  live_time:
    enable: true
    prefix: 本博客已运行
    suffix: (●'◡'●)
    start_time: "2020-06-25T20:49:30"
  custom_text: <a href="https://icp.gov.moe/?keyword=20228015" target="_blank">萌ICP备20228015号</a>

say:
  enable: true
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

mourn:
  enable: true
  days:
    - "4-4"
    - "12-13"
    - "7-7"
    - "11-30" # 江

girls:
  enable: false

comment:
  enable: true

github_issues:
  enable: false
  username: chitang233
  repository: chitang233
  filters: is:issue

utterances:
  enable: true
  repo: chitang233/chitang233
  issue-term: pathname
  label: comment
  theme: github-light

# search
# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: true
  src: /js/search/local-search.js

busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line

wordcount:
  enable: true
  count: true
  time: true

wordcloud:
  enable: true

medium_zoom: true



