name: Apply FreeCDN
on:
  push:
    branches:
      - pages
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        run: sudo npm install freecdn -g

      - name: Generate List
        run: |
          export FREECDN_RESOLVE=4
          freecdn find --save --with-urls urls.txt
          echo "open_timeout=0" > urls.txt
      - name: Generate JavaScript
        run: freecdn js --make

      - name: Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"  
          git add .
          git commit -m "Update FreeCDN"
          git push